#!/bin/sh
#
# Start emtpy urandom
#

start() {
	echo "Starting empty urandom: OK"
}

stop() {
	echo "Stoping empty urandom: OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
