
- title: 《360° 剖析 Linux ELF》视频课程 —— Linux 程序员基本素养训练课
  permalink: https://cctalk.com/m/group/88089283
  description: 以程序格式 ELF 为切入点，通过实验的方式学习 Linux 程序链接、装载、运行与调试原理，由泰晓科技技术社区创始人授课。
  group: products

- title: Linux 知识星球 —— 泰晓科技 VIP 知识频道
  permalink: https://cctalk.com/m/group/89433087
  description: 专属 Linux 原创内容与工作机会；VIP 微信群与 20 位嘉宾老师；泰晓学院视频课程专属优惠券；其他福利和机会。
  group: products

- title: Linux Lab 真盘 —— 免安装、即插即用 Linux 内核与系统实验盘
  permalink: https://shop155917374.taobao.com/
  description: 可以在 64 位 X86 台式机、笔记本、macBook 上即插即用，可以作为独立系统使用，也可以作为双系统使用，可用于学习汇编、C语言、Shell、Uboot、Linux内核与嵌入式 Linux 系统等。
  group: products

- title: Linux Lab 真板 —— 适配过 Linux Lab 的嵌入式硬件开发板
  permalink: https://shop155917374.taobao.com/
  description: 适配过 Linux Lab 开发环境，可以即时开展相关实验，免去复杂的环境搭建和实验过程。
  group: products
