# Decompress

all:
	wget -c http://dev.lemote.com/files/resource/toolchain/cross-compile/cross-loongson-gcc4_5_2-binutils2_21.tar.bz2
	tar jxf cross-loongson-gcc4_5_2-binutils2_21.tar.bz2

clean:
	rm -rf cross-loongson-4.5.2/
