# Makefile.lib

CCORI ?= bootlin

ifeq ($(CCORI), bootlin)
  CCPRE  ?= mips-linux-
  CCVER  ?= 2018.11-1
  CCPATH ?= $(PREBUILT_TOOLCHAINS)/mipsel/mips32--uclibc--stable-$(CCVER)/bin
endif

ifeq ($(CCORI), mips)
  CCPRE  ?= mips-img-elf-
  CCVER  ?= 2018.09-03
  CCPATH ?= $(PREBUILT_TOOLCHAINS)/mipsel/mips-img-elf/2018.09-03/bin
endif
