# make toolchain CCORI=mips b=mipsel/malta
# export PATH=/labs/linux-lab/prebuilt/toolchains/mipsel/mips-img-elf/2018.09-03/bin/:$PATH
# CROSS_COMPILE ?= mips-img-elf-

MABI    := 32
OFORMAT := elf32ltsmip

include ../common.mk
