# ref: https://www.sifive.com/blog/all-aboard-part-1-compiler-args
# Compile options, please refer to linux-stable/arch/riscv/Makefile

MARCH   := rv64im
MABI    := lp64
OFORMAT := elf64lriscv

include ../common.mk
