
TC_ORIG ?= bootlin

ifeq ($(TC_ORIG), bootlin)
  TC_VERSION ?= 2018.11-1

  TC_BASE = powerpc-e500mc--uclibc--stable-$(TC_VERSION)
  TC_URL  = https://toolchains.bootlin.com/downloads/releases/toolchains/powerpc-e500mc/tarballs/$(TC_BASE).tar.bz2
endif

include ../Makefile.lib
