#!/bin/sh
#
# Start sharing
#

[ -r /etc/default/sharing ] && . /etc/default/sharing

start() {
	printf "Starting sharing: "
	$START_SHARING
	echo "OK"
}

stop() {
	printf "Stopping sharing: "
	$STOP_SHARING
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
