#!/bin/sh
#
# Start testing
#

[ -r /etc/default/testing ] && . /etc/default/testing

start() {
	$START_TESTING
}

stop() {
	$STOP_TESTING
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit $?
