#!/bin/bash
#
# Switch ruby to a specified version
#

version=$1
[ -z "$version" ] && version=2.0

pushd /usr/bin/

for i in ri ruby gem erb irb rake rdoc testrb
do
	ln -sf ${i}${version} ${i}
        ls ${i}
done

popd

gem update --system
gem pristine --all
