# Core Makefile.lib

TC_TAR = $(notdir $(TC_URL))

ifeq ($(findstring .tar.xz, $(TC_TAR)),.tar.xz)
  TAR_OPTS = Jxvf
endif

ifeq ($(findstring .tar.bz2, $(TC_TAR)),.tar.bz2)
  TAR_OPTS = jxvf
endif

ifeq ($(findstring .tar.gz, $(TC_TAR)),.tar.gz)
  TAR_OPTS = zxvf
endif

ifeq ($(findstring .tgz, $(TC_TAR)),.tgz)
  TAR_OPTS = zxvf
endif

all:
	wget -c $(TC_URL)
	tar $(TAR_OPTS) $(TC_TAR)

clean:
	rm -rf $(TC_BASE)
